name: 'dbt_snowflake_poc'
version: '1.0.0'
config-version: 2


profile: 'airflow_dbt_poc2'


model-paths: ["dbt/models"]
analysis-paths: ["dbt/analyses"]
test-paths: ["dbt/tests"]
seed-paths: ["dbt/seeds"]
macro-paths: ["dbt/macros"]
snapshot-paths: ["dbt/snapshots"]

target-path: "dbt/target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "dbt/target"
  - "dbt/dbt_packages"

on-run-end:
  - "{{ log_model_runs(results) }}"

models:
  dbt_snowflake_poc:
    01_stage:
      +database: PROVIDER_SYSTEMS
      wealth:
        +database: PROVIDER_SYSTEMS
        +schema: WEALTH_ARCHIVE
        +materialized: table
      vendor_db:
        +database: PROVIDER_SYSTEMS
        +schema: VENDOR_DB_ARCHIVE
        +materialized: table

    02_integration:
      +database: DATA_PLATFORM_INTEGRATION
      wealth:
        Account:
          +database: DATA_PLATFORM_INTEGRATION
          +schema: ACCOUNT
          +materialized: table
        Client:
          +database: DATA_PLATFORM_INTEGRATION
          +schema: CLIENT
          +materialized: table
        Fund:
          +database: DATA_PLATFORM_INTEGRATION
          +schema: FUND
          +materialized: table
        Transaction:
          +database: DATA_PLATFORM_INTEGRATION
          +schema: TRANSACTION
          +materialized: table
    03_delivery_zone:
      +database: INTERNAL_DELIVERY_ZONE
      internal_delivery_zone:
        Client:
          +database: INTERNAL_DELIVERY_ZONE
          +schema: CLIENT
          +materialized: table
        Account:
          +database: INTERNAL_DELIVERY_ZONE
          +schema: ACCOUNT
          +materialized: table
        Fund:
          +database: INTERNAL_DELIVERY_ZONE
          +schema: FUND
          +materialized: table
        Transaction:
          +database: INTERNAL_DELIVERY_ZONE
          +schema: TRANSACTION
          +materialized: table
    04_deployments:
      +database: MONITOR
      +enabled: true
      +materialized: 'ephemeral'