sources:
  - name: WEALTH
    database:  "{{ env_var('DBT_ENV_PROVIDER_SYSTEMS') }}"
    schema: WEALTH  
    tables:
      - name: CUSTOMER
      - name: FUND_NAV
      - name: CUSTOMER_INVESTMENT_ACCOUNT
      - name: FUND
      - name: TRANSACTIONS

  - name: VENDOR_DB
    database: "{{ env_var('DBT_ENV_PROVIDER_SYSTEMS') }}"  
    schema: VENDOR_DB  
    tables:
      - name: CUSTOMER
      - name: FUND_NAV
      - name: CUSTOMER_INVESTMENT_ACCOUNT
      - name: FUND
      - name: TRANSACTIONS
