sources:
  - name: WEALTH
    database:  "PROVIDER_SYSTEMS_{{ env_var('DBT_TARGET', 'DEV') | upper }}"
    schema: WEALTH  
    tables:
      - name: CUSTOMER
      - name: FUND_NAV
      - name: CUSTOMER_INVESTMENT_ACCOUNT
      - name: FUND
      - name: TRANSACTIONS

  - name: VENDOR_DB
    database: "PROVIDER_SYSTEMS_{{ env_var('DBT_TARGET', 'DEV') | upper }}" 
    schema: VENDOR_DB  
    tables:
      - name: CUSTOMER
      - name: FUND_NAV
      - name: CUSTOMER_INVESTMENT_ACCOUNT
      - name: FUND
      - name: TRANSACTIONS
