{{ config(materialized='table') }}

SELECT
    ROW_NUMBER() OVER (ORDER BY FUND_CODE) AS SECURITY_SK,

    FUND_CODE,
    NULL AS PLAN_CODE,

    FUND_NAME AS SECURITY_NAME,
    PRODUCT_CATEGORY_CODE AS PRODUCT_CATEGORY,
    SUB_ASSET_CODE AS SUB_ASSET_CLASS,
    DIVIDEND_OPTION,
    FUND_CURRENCY,
    AMC_CODE,
    ISIN_CODE,

    CURRENT_TIMESTAMP() AS DW_LOAD_TIMESTAMP

FROM {{ ref('WEALTH_FUND') }}